# this docker compose is compatible with Adaptive release v0.2.1
name: adaptive
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=adaptive
      - POSTGRES_DB=adaptive
    volumes:
      - ${DB_DATA_HOST_PATH:-./db_data}:/var/lib/postgresql/data  
  volume-init:
    image: alpine
    command: [ "sh", "-c", "chmod -R 777 /model_registry && chown -R 1002:1002 /shared /workdir" ]
    volumes:
      - ${MODEL_REGISTRY_HOST_PATH:-./model_registry}:/model_registry
      - ./shared:/shared
      - ./workdir:/workdir
    restart: "no"
  harmony:
    runtime: nvidia
    image: ${IMAGE_REPO}:${HARMONY_IMAGE_TAG}
    depends_on:
      volume-init:
        condition: service_completed_successfully
    environment:
      - ORDINAL=0
      - MASTER_ADDR=127.0.0.1
      - WORLD_SIZE=${GPU_COUNT:-1}
      - GPU_COUNT=${GPU_COUNT:-1}
      - HARMONY_SETTINGS_SHARED_MASTER_WORKER_FOLDER=/shared
      - HARMONY_SETTING_WORKING_DIR=/workdir
      - HARMONY_SETTING_MODEL_REGISTRY_ROOT=/model_registry
    shm_size: 2g
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ${MODEL_REGISTRY_HOST_PATH:-./model_registry}:/model_registry
      - ./shared:/shared
      - ./workdir:/workdir
    ports:
      - 50053:50053
    restart: on-failure
  control-plane:
    depends_on:
      volume-init:
        condition: service_completed_successfully
      harmony: 
        condition: service_started
      db: 
        condition: service_started
    image: ${IMAGE_REPO}:${CONTROL_PLANE_IMAGE_TAG} 
    ports:
      - 9000:9000
    volumes:
      - ./shared:/shared
    environment:
      - ADAPTIVE_APP__SECRET=changeme-secret-db40431e-c2fd-48a6-acd5-854232c2ed94-01dd4d01-dc7b-4315
      - ADAPTIVE_AUTH__ADMINS=${ADMINS}
      - ADAPTIVE_AUTH__DEFAULT_TEAM=default
      - ADAPTIVE_AUTH__DEFAULT_ROLE=admin
      - ADAPTIVE_AUTH__SESSION__SECURE=true
      - ADAPTIVE_AUTH__SESSION__EXPIRATION_SECONDS=518400
      - ADAPTIVE_AUTH__OIDC__PROVIDERS=${OIDC_PROVIDERS}
      - ADAPTIVE_DB__RUN_MIGRATIONS=true
      - ADAPTIVE_DB__URL=postgresql://adaptive:${DB_PASSWORD}@db:5432/adaptive
      - ADAPTIVE_HTTP_CLIENT__TIMEOUT_SECS=90
      - ADAPTIVE_SERVER__BIND=0.0.0.0:9000
      - ADAPTIVE_SERVER__ROOT_URL=${ROOT_URL}
      - ADAPTIVE_HARMONY__URL=http://harmony:50053
      - ADAPTIVE_HARMONY__SHARED_DIRECTORY__PATH=/shared
      - HARMONY_SETTING_MODEL_REGISTRY_ROOT=/model_registry
    restart: on-failure

