global:
  scrape_interval: 30s # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  scrape_timeout: 10s # Timeout after 10 seconds

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files specifies a list of files from which rules are read
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing endpoints to scrape
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "control-plane"
    static_configs:
      - targets: ["control-plane:9009"]

  - job_name: "harmony"
    static_configs:
      - targets: ["harmony:50053"]
