services:
  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/datasources/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/grafana/plugins/app.yaml:/etc/grafana/provisioning/plugins/app.yaml
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SERVER_DOMAIN=localhost:9000
      - GF_SERVER_ROOT_URL=http://localhost:9000/monitoring/
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall lokiLogsDataplane
      - GF_PLUGINS_PREINSTALL=grafana-lokiexplore-app@@https://storage.googleapis.com/integration-artifacts/grafana-lokiexplore-app/grafana-lokiexplore-app-latest.zip

  loki:
    image: grafana/loki:3.4
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/loki.yaml:ro
      - loki_data:/loki

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - 12345:12345
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - alloy_data:/var/lib/alloy
      - ../workdir/job_logs/:/logs/
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  loki_data:
  alloy_data:
  prometheus_data:
  grafana_data:
